version: "3.8"

services:
  unicourt-ui:
    image: node:20-alpine
    container_name: unicourt-ui
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "4200:4200"
    command: sh -c "npm install && npx ng serve --host 0.0.0.0"
